import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import 'package:personal_financial_assistant/core/widgets/financial_widgets.dart';
import 'package:personal_financial_assistant/core/widgets/responsive_center.dart';
import 'package:personal_financial_assistant/features/accounts/account.dart';
import 'package:personal_financial_assistant/features/accounts/presentation/providers/account_providers.dart';
import 'package:personal_financial_assistant/features/categories/category.dart';
import 'package:personal_financial_assistant/features/categories/presentation/providers/category_providers.dart';
import 'package:personal_financial_assistant/features/recurring_transactions/domain/models/recurring_transaction_rule.dart';
import 'package:personal_financial_assistant/features/recurring_transactions/presentation/providers/recurring_transaction_providers.dart';
import 'package:personal_financial_assistant/features/recurring_transactions/presentation/widgets/add_edit_recurring_transaction_dialog.dart';
import 'package:personal_financial_assistant/features/recurring_transactions/presentation/widgets/due_occurrences_banner.dart';
import 'package:personal_financial_assistant/features/transactions/transaction.dart';

class RecurringTransactionsScreen extends ConsumerStatefulWidget {
  const RecurringTransactionsScreen({super.key});

  @override
  ConsumerState<RecurringTransactionsScreen> createState() =>
      _RecurringTransactionsScreenState();
}

class _RecurringTransactionsScreenState
    extends ConsumerState<RecurringTransactionsScreen> {
  String _selectedFilter =
      'all'; // 'all', 'income', 'expense', 'active', 'paused'

  void _showAddRuleDialog([TransactionType type = TransactionType.expense]) {
    showDialog(
      context: context,
      builder: (context) =>
          AddEditRecurringTransactionDialog(initialType: type),
    );
  }

  void _showEditRuleDialog(RecurringTransactionRule rule) {
    showDialog(
      context: context,
      builder: (context) => AddEditRecurringTransactionDialog(rule: rule),
    );
  }

  Future<void> _confirmDeleteRule(RecurringTransactionRule rule) async {
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Delete Recurring Rule'),
        content: Text(
          'Are you sure you want to delete "${rule.name}"?\n\n'
          'Past recorded transactions generated by this rule will be preserved.',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).pop(false),
            child: const Text('Cancel'),
          ),
          FilledButton(
            style: FilledButton.styleFrom(backgroundColor: Colors.red),
            onPressed: () => Navigator.of(context).pop(true),
            child: const Text('Delete Rule'),
          ),
        ],
      ),
    );

    if (confirmed == true && mounted) {
      final success = await ref
          .read(recurringTransactionControllerProvider.notifier)
          .deleteRule(rule.id);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(
              success ? 'Rule "${rule.name}" deleted' : 'Failed to delete rule',
            ),
            backgroundColor: success ? Colors.green[700] : Colors.red,
          ),
        );
      }
    }
  }

  Future<void> _processRuleNow(RecurringTransactionRule rule) async {
    final count = await ref
        .read(recurringTransactionControllerProvider.notifier)
        .processSingleRule(rule);
    if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            count > 0
                ? 'Recorded $count recurring transaction for "${rule.name}"!'
                : 'No occurrences due for "${rule.name}".',
          ),
          backgroundColor: count > 0 ? Colors.green[700] : null,
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;
    final rulesAsync = ref.watch(recurringTransactionsStreamProvider);
    final categoriesAsync = ref.watch(categoriesStreamProvider);
    final accountsAsync = ref.watch(accountsStreamProvider);

    return Scaffold(
      body: ResponsiveCenter(
        maxWidth: 1000,
        padding: const EdgeInsets.only(
          left: 16.0,
          right: 16.0,
          top: 16.0,
          bottom: 80.0,
        ),
        child: Column(
          children: [
            PageHeader(
              title: 'Recurring Transactions',
              subtitle: 'Manage automated income and expense commitments with deterministic catch-up.',
              action: FilledButton.icon(
                onPressed: () => _showAddRuleDialog(),
                icon: const Icon(Icons.add_rounded),
                label: const Text('Add Recurring Rule'),
              ),
            ),
            const DueOccurrencesBanner(),
            Expanded(
              child: rulesAsync.when(
                data: (rules) {
                  final activeIncome = rules
                      .where((r) => r.active && r.isIncome)
                      .fold<double>(0.0, (sum, r) => sum + r.amount);
                  final activeExpense = rules
                      .where((r) => r.active && r.isExpense)
                      .fold<double>(0.0, (sum, r) => sum + r.amount);
                  final netMonthly = activeIncome - activeExpense;

                  final categoriesMap = {
                    for (final c
                        in (categoriesAsync.value ??
                            Category.generateDefaults('temp')))
                      c.id: c.name,
                  };

                  final accountsMap = {
                    for (final a in (accountsAsync.value ?? <Account>[]))
                      a.id: a.name,
                  };

                  // Filter logic
                  var filteredRules = rules;
                  if (_selectedFilter == 'income') {
                    filteredRules = rules.where((r) => r.isIncome).toList();
                  } else if (_selectedFilter == 'expense') {
                    filteredRules = rules.where((r) => r.isExpense).toList();
                  } else if (_selectedFilter == 'active') {
                    filteredRules = rules.where((r) => r.active).toList();
                  } else if (_selectedFilter == 'paused') {
                    filteredRules = rules.where((r) => !r.active).toList();
                  }

                  return RefreshIndicator(
                    onRefresh: () async {
                      ref.invalidate(recurringTransactionsStreamProvider);
                    },
                    child: ListView(
                      physics: const AlwaysScrollableScrollPhysics(),
                      children: [
                        // Summary Metric Cards
                        Card(
                          elevation: 0,
                          color: colorScheme.surfaceContainerHighest.withValues(
                            alpha: 0.5,
                          ),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(16),
                            side: BorderSide(
                              color: colorScheme.outlineVariant.withValues(
                                alpha: 0.5,
                              ),
                            ),
                          ),
                          child: Padding(
                            padding: const EdgeInsets.all(16.0),
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Row(
                                  children: [
                                    Icon(
                                      Icons.insights_rounded,
                                      color: colorScheme.primary,
                                      size: 20,
                                    ),
                                    const SizedBox(width: 8),
                                    Expanded(
                                      child: Text(
                                        'Active Recurring Commitments',
                                        style: theme.textTheme.titleSmall
                                            ?.copyWith(
                                              fontWeight: FontWeight.bold,
                                            ),
                                        maxLines: 1,
                                        overflow: TextOverflow.ellipsis,
                                      ),
                                    ),
                                  ],
                                ),
                                const SizedBox(height: 12),
                                Builder(
                                  builder: (context) {
                                    final isNarrow =
                                        MediaQuery.sizeOf(context).width < 600;
                                    final incomeTile = _MetricTile(
                                      label: 'Monthly Recurring Income',
                                      amount: activeIncome,
                                      isPositive: true,
                                      icon: Icons.arrow_downward_rounded,
                                    );
                                    final expenseTile = _MetricTile(
                                      label: 'Monthly Recurring Expenses',
                                      amount: activeExpense,
                                      isPositive: false,
                                      icon: Icons.arrow_upward_rounded,
                                    );
                                    final netTile = _MetricTile(
                                      label: 'Net Recurring Cash Flow',
                                      amount: netMonthly,
                                      isPositive: netMonthly >= 0,
                                      icon:
                                          Icons.account_balance_wallet_outlined,
                                    );

                                    if (isNarrow) {
                                      return Column(
                                        children: [
                                          incomeTile,
                                          const Divider(height: 16),
                                          expenseTile,
                                          const Divider(height: 16),
                                          netTile,
                                        ],
                                      );
                                    }

                                    return Row(
                                      children: [
                                        Expanded(child: incomeTile),
                                        const SizedBox(width: 12),
                                        Expanded(child: expenseTile),
                                        const SizedBox(width: 12),
                                        Expanded(child: netTile),
                                      ],
                                    );
                                  },
                                ),
                              ],
                            ),
                          ),
                        ),
                        const SizedBox(height: 16),

                        // Filter Chips
                        SingleChildScrollView(
                          scrollDirection: Axis.horizontal,
                          child: Row(
                            children: [
                              _buildFilterChip('all', 'All (${rules.length})'),
                              const SizedBox(width: 8),
                              _buildFilterChip(
                                'income',
                                'Income (${rules.where((r) => r.isIncome).length})',
                              ),
                              const SizedBox(width: 8),
                              _buildFilterChip(
                                'expense',
                                'Expenses (${rules.where((r) => r.isExpense).length})',
                              ),
                              const SizedBox(width: 8),
                              _buildFilterChip(
                                'active',
                                'Active (${rules.where((r) => r.active).length})',
                              ),
                              const SizedBox(width: 8),
                              _buildFilterChip(
                                'paused',
                                'Paused (${rules.where((r) => !r.active).length})',
                              ),
                            ],
                          ),
                        ),
                        const SizedBox(height: 16),

                        // Content
                        if (rules.isEmpty) ...[
                          _buildEmptyState(
                            theme: theme,
                            colorScheme: colorScheme,
                            title: 'No Recurring Rules Configured',
                            description: 'Automate regular income like your Monthly Salary or recurring expenses like Rent, Subscriptions, and Bills so you never have to record them manually.',
                            onAdd: () => _showAddRuleDialog(),
                          ),
                        ] else if (filteredRules.isEmpty) ...[
                          _buildEmptyState(
                            theme: theme,
                            colorScheme: colorScheme,
                            title: 'No Matching Rules',
                            description:
                                'No recurring rules match the selected filter.',
                            onAdd: () =>
                                setState(() => _selectedFilter = 'all'),
                            buttonText: 'Show All Rules',
                          ),
                        ] else ...[
                          ...filteredRules.map((rule) {
                            return _buildRuleCard(
                              rule: rule,
                              theme: theme,
                              colorScheme: colorScheme,
                              categoryName:
                                  categoriesMap[rule.categoryId] ?? 'Category',
                              accountName:
                                  accountsMap[rule.accountId] ?? 'Account',
                            );
                          }),
                        ],
                        const SizedBox(height: 80),
                      ],
                    ),
                  );
                },
                loading: () => const Center(child: CircularProgressIndicator()),
                error: (e, _) => Center(
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      const Icon(
                        Icons.error_outline,
                        size: 48,
                        color: Colors.red,
                      ),
                      const SizedBox(height: 12),
                      Text('Error loading recurring rules: $e'),
                      const SizedBox(height: 16),
                      FilledButton(
                        onPressed: () =>
                            ref.invalidate(recurringTransactionsStreamProvider),
                        child: const Text('Retry'),
                      ),
                    ],
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildFilterChip(String filterKey, String label) {
    final isSelected = _selectedFilter == filterKey;
    return ChoiceChip(
      label: Text(label),
      selected: isSelected,
      onSelected: (_) => setState(() => _selectedFilter = filterKey),
    );
  }

  Widget _buildEmptyState({
    required ThemeData theme,
    required ColorScheme colorScheme,
    required String title,
    required String description,
    required VoidCallback onAdd,
    String buttonText = 'Add Recurring Rule',
  }) {
    return Card(
      elevation: 0,
      color: colorScheme.surfaceContainerLow,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(16),
        side: BorderSide(
          color: colorScheme.outlineVariant.withValues(alpha: 0.5),
        ),
      ),
      child: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 36),
        child: Column(
          children: [
            Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: colorScheme.primaryContainer.withValues(alpha: 0.5),
                shape: BoxShape.circle,
              ),
              child: Icon(
                Icons.repeat_rounded,
                size: 40,
                color: colorScheme.primary,
              ),
            ),
            const SizedBox(height: 16),
            Text(
              title,
              style: theme.textTheme.titleMedium?.copyWith(
                fontWeight: FontWeight.bold,
              ),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 8),
            Text(
              description,
              style: theme.textTheme.bodyMedium?.copyWith(
                color: colorScheme.onSurfaceVariant,
              ),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 20),
            Wrap(
              spacing: 12,
              runSpacing: 12,
              alignment: WrapAlignment.center,
              children: [
                FilledButton.icon(
                  onPressed: onAdd,
                  icon: const Icon(Icons.add),
                  label: Text(buttonText),
                ),
                OutlinedButton.icon(
                  onPressed: () => _showAddRuleDialog(TransactionType.income),
                  icon: const Icon(Icons.wallet, color: Colors.green),
                  label: const Text('Add Salary'),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildRuleCard({
    required RecurringTransactionRule rule,
    required ThemeData theme,
    required ColorScheme colorScheme,
    required String categoryName,
    required String accountName,
  }) {
    final isDue = rule.isDue();
    final dateFormat = DateFormat('dd MMM yyyy');

    return Card(
      margin: const EdgeInsets.only(bottom: 12),
      elevation: 0,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(12),
        side: BorderSide(
          color: isDue
              ? colorScheme.primary
              : colorScheme.outlineVariant.withValues(alpha: 0.6),
          width: isDue ? 1.5 : 1.0,
        ),
      ),
      child: Padding(
        padding: const EdgeInsets.all(14.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Header Row: Type Icon, Title & Amount
            Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(
                    color: (rule.isIncome ? Colors.green : Colors.red)
                        .withValues(alpha: 0.12),
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: Icon(
                    rule.isIncome
                        ? Icons.arrow_downward_rounded
                        : Icons.arrow_upward_rounded,
                    color: rule.isIncome ? Colors.green : Colors.red,
                    size: 20,
                  ),
                ),
                const SizedBox(width: 10),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        rule.name,
                        style: theme.textTheme.titleMedium?.copyWith(
                          fontWeight: FontWeight.bold,
                          decoration: rule.active
                              ? null
                              : TextDecoration.lineThrough,
                        ),
                        maxLines: 1,
                        overflow: TextOverflow.ellipsis,
                      ),
                      Text(
                        '$categoryName • $accountName',
                        style: theme.textTheme.bodySmall?.copyWith(
                          color: colorScheme.onSurfaceVariant,
                        ),
                        maxLines: 1,
                        overflow: TextOverflow.ellipsis,
                      ),
                    ],
                  ),
                ),
                const SizedBox(width: 8),
                Text(
                  NumberFormat.currency(
                    locale: 'en_IN',
                    symbol: '₹ ',
                  ).format(rule.amount),
                  style: theme.textTheme.titleMedium?.copyWith(
                    fontWeight: FontWeight.bold,
                    color: rule.isIncome ? Colors.green : Colors.red,
                  ),
                ),
              ],
            ),
            const SizedBox(height: 10),
            const Divider(height: 1),
            const SizedBox(height: 10),

            // Metadata Row: Frequency, Next occurrence, and Badges
            Wrap(
              spacing: 8,
              runSpacing: 6,
              crossAxisAlignment: WrapCrossAlignment.center,
              children: [
                Chip(
                  label: Text(
                    rule.frequencyDescription,
                    style: const TextStyle(fontSize: 12),
                  ),
                  padding: EdgeInsets.zero,
                  visualDensity: VisualDensity.compact,
                  materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
                ),
                Chip(
                  label: Text(
                    'Next: ${dateFormat.format(rule.nextOccurrence)}',
                    style: TextStyle(
                      fontSize: 12,
                      fontWeight: isDue ? FontWeight.bold : FontWeight.normal,
                      color: isDue ? colorScheme.primary : null,
                    ),
                  ),
                  avatar: Icon(
                    Icons.event_rounded,
                    size: 14,
                    color: isDue ? colorScheme.primary : null,
                  ),
                  padding: EdgeInsets.zero,
                  visualDensity: VisualDensity.compact,
                  materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
                ),
                if (isDue)
                  Container(
                    padding: const EdgeInsets.symmetric(
                      horizontal: 8,
                      vertical: 3,
                    ),
                    decoration: BoxDecoration(
                      color: Colors.amber.shade700,
                      borderRadius: BorderRadius.circular(6),
                    ),
                    child: const Text(
                      'DUE NOW',
                      style: TextStyle(
                        fontSize: 10,
                        fontWeight: FontWeight.bold,
                        color: Colors.white,
                      ),
                    ),
                  ),
                if (!rule.active)
                  Container(
                    padding: const EdgeInsets.symmetric(
                      horizontal: 8,
                      vertical: 3,
                    ),
                    decoration: BoxDecoration(
                      color: Colors.grey.shade600,
                      borderRadius: BorderRadius.circular(6),
                    ),
                    child: const Text(
                      'PAUSED',
                      style: TextStyle(
                        fontSize: 10,
                        fontWeight: FontWeight.bold,
                        color: Colors.white,
                      ),
                    ),
                  ),
              ],
            ),
            const SizedBox(height: 10),

            // Action Buttons Row
            Wrap(
              alignment: WrapAlignment.end,
              crossAxisAlignment: WrapCrossAlignment.center,
              spacing: 6,
              runSpacing: 6,
              children: [
                if (isDue)
                  FilledButton.tonalIcon(
                    onPressed: () => _processRuleNow(rule),
                    icon: const Icon(Icons.check, size: 16),
                    label: const Text('Record Due'),
                    style: FilledButton.styleFrom(
                      visualDensity: VisualDensity.compact,
                    ),
                  ),
                IconButton(
                  tooltip: rule.active ? 'Pause Rule' : 'Resume Rule',
                  icon: Icon(
                    rule.active
                        ? Icons.pause_circle_outline_rounded
                        : Icons.play_circle_outline_rounded,
                    size: 20,
                  ),
                  onPressed: () => ref
                      .read(recurringTransactionControllerProvider.notifier)
                      .toggleStatus(rule.id, !rule.active),
                  visualDensity: VisualDensity.compact,
                ),
                IconButton(
                  tooltip: 'Edit Rule',
                  icon: const Icon(Icons.edit_outlined, size: 20),
                  onPressed: () => _showEditRuleDialog(rule),
                  visualDensity: VisualDensity.compact,
                ),
                IconButton(
                  tooltip: 'Delete Rule',
                  icon: const Icon(
                    Icons.delete_outline_rounded,
                    size: 20,
                    color: Colors.red,
                  ),
                  onPressed: () => _confirmDeleteRule(rule),
                  visualDensity: VisualDensity.compact,
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

class _MetricTile extends StatelessWidget {
  final String label;
  final double amount;
  final bool isPositive;
  final IconData icon;

  const _MetricTile({
    required this.label,
    required this.amount,
    required this.isPositive,
    required this.icon,
  });

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(icon, size: 14, color: colorScheme.onSurfaceVariant),
            const SizedBox(width: 4),
            Flexible(
              child: Text(
                label,
                style: theme.textTheme.bodySmall?.copyWith(
                  color: colorScheme.onSurfaceVariant,
                ),
                maxLines: 1,
                overflow: TextOverflow.ellipsis,
              ),
            ),
          ],
        ),
        const SizedBox(height: 4),
        Text(
          NumberFormat.currency(
            locale: 'en_IN',
            symbol: '₹ ',
          ).format(amount.abs()),
          style: theme.textTheme.titleMedium?.copyWith(
            fontWeight: FontWeight.bold,
            color: isPositive ? Colors.green : Colors.red,
          ),
          maxLines: 1,
          overflow: TextOverflow.ellipsis,
        ),
      ],
    );
  }
}
