// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC09lNxoi31YvMMSBRzBPwDkTC1qSZ-DZI',
    appId: '1:19389275039:web:7e88bf52e4c6de5a333baa',
    messagingSenderId: '19389275039',
    projectId: 'msd-financial-assistant',
    authDomain: 'msd-financial-assistant.firebaseapp.com',
    storageBucket: 'msd-financial-assistant.firebasestorage.app',
    measurementId: 'G-C2PLYNHVD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoA2RR36V6sFULWORVpSdVZGVcqq7xjrU',
    appId: '1:19389275039:android:27dfb7c677f82e69333baa',
    messagingSenderId: '19389275039',
    projectId: 'msd-financial-assistant',
    storageBucket: 'msd-financial-assistant.firebasestorage.app',
  );
}
