import 'package:flutter/material.dart';
import 'package:personal_financial_assistant/core/constants/app_constants.dart';

class FinancialDisclaimerScreen extends StatelessWidget {
  const FinancialDisclaimerScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;

    return Scaffold(
      appBar: AppBar(title: const Text('Financial Disclaimer')),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(20.0),
          child: Center(
            child: ConstrainedBox(
              constraints: const BoxConstraints(maxWidth: 720),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Card(
                    color: colorScheme.surfaceContainerHighest.withValues(
                      alpha: 0.5,
                    ),
                    child: Padding(
                      padding: const EdgeInsets.all(16.0),
                      child: Row(
                        children: [
                          Icon(
                            Icons.info_outline,
                            color: colorScheme.primary,
                            size: 28,
                          ),
                          const SizedBox(width: 14),
                          Expanded(
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Text(
                                  'Financial & Decision Disclaimer',
                                  style: theme.textTheme.titleMedium?.copyWith(
                                    fontWeight: FontWeight.bold,
                                  ),
                                ),
                                const SizedBox(height: 4),
                                Text(
                                  '${AppConstants.appName} • Software Assistant Notice',
                                  style: theme.textTheme.bodySmall?.copyWith(
                                    color: colorScheme.onSurfaceVariant,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                  const SizedBox(height: 24),

                  _buildSection(
                    theme,
                    title: 'Software Calculations & Informational Purpose',
                    content:
                        '${AppConstants.appName} provides software-based calculations and data organization tools intended solely to assist users in tracking their personal finances. All outputs, calculations, and future informational insights are generated by software rules based on user-provided inputs.',
                  ),
                  _buildSection(
                    theme,
                    title: 'Not Professional Advice',
                    content:
                        'The application and its content do NOT constitute formal financial, investment, tax, legal, or accounting advice. ${AppConstants.appName} is not a financial adviser, broker, bank, or tax consultant.',
                  ),
                  _buildSection(
                    theme,
                    title: 'User Input Dependency & Verification',
                    content: 'The accuracy of all totals and summaries depends entirely on the accuracy and completeness of data entered by the user. Users should independently verify important balances and consult qualified professionals before making significant financial decisions.',
                  ),
                  _buildSection(
                    theme,
                    title: 'Non-Custodial Nature',
                    content: 'The application does not hold, manage, or transfer money. Users retain sole control and responsibility for their bank accounts and money transactions.',
                  ),
                  const SizedBox(height: 32),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildSection(
    ThemeData theme, {
    required String title,
    required String content,
  }) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 20.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: theme.textTheme.titleMedium?.copyWith(
              fontWeight: FontWeight.bold,
              color: theme.colorScheme.primary,
            ),
          ),
          const SizedBox(height: 8),
          Text(
            content,
            style: theme.textTheme.bodyMedium?.copyWith(
              height: 1.5,
              color: theme.colorScheme.onSurface,
            ),
          ),
        ],
      ),
    );
  }
}
